Vidly2/Vidly2/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vidly2.Controllers
{
    [AllowAnonymous]
    public class RentalsController : Controller
    {
        // GET: Rentals
        public ActionResult New()
        {
            return View();
        }
    }
}

Vidly2/Vidly2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Vidly</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavBar");
    <div class="container body-content">
        <hr />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vidly</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")    
    @RenderSection("scripts", required: false)
</body>
</html> 

Vidly2/Vidly2/Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark bg-primary">
    <a class="navbar-brand" href="#">Vidly</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation" style="">
        <span class="navbar-toggler-icon"></span>
    </button>

    @if (Request.IsAuthenticated)
    {
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <span class="nav-link">@Html.ActionLink("New Rental", "New", "Rentals")</span>
                </li>
                <li class="nav-item active">
                    <span class="nav-link">@Html.ActionLink("Customers", "Index", "Customers")</span>
                </li>
                <li class="nav-item">
                    <span class="nav-link">@Html.ActionLink("Movies", "Index", "Movies")</span>
                </li>
                <li class="nav-item">
                    <span class="nav-link">@Html.ActionLink("Contato", "Contact", "Home")</span>
                </li>
            </ul>
        </div>
    }

    @Html.Partial("_LoginPartial")
</nav>